# Generated by Django 6.0.2 on 2026-02-17 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_phone_alter_user_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Bekat nomi')),
                ('latitude', models.FloatField(verbose_name='Kenglik (Lat)')),
                ('longitude', models.FloatField(verbose_name='Uzunlik (Long)')),
                ('description', models.TextField(blank=True, verbose_name="Batafsil ma'lumot")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bekat',
                'verbose_name_plural': 'Bekatlar',
            },
        ),
    ]
