# Generated by Django 6.0.2 on 2026-02-17 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='dead_end_tracks',
            field=models.IntegerField(default=0, verbose_name="Tupik yo'llar"),
        ),
        migrations.AddField(
            model_name='station',
            name='insulating_joints',
            field=models.IntegerField(default=0, verbose_name='Izostiklar soni'),
        ),
        migrations.AddField(
            model_name='station',
            name='main_tracks',
            field=models.IntegerField(default=0, verbose_name="Shundan asosiy yo'llar"),
        ),
        migrations.AddField(
            model_name='station',
            name='manager_name',
            field=models.CharField(default=' ', max_length=150, verbose_name="Mas'ul F.I.O"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='manager_phone',
            field=models.CharField(default=' ', max_length=25, verbose_name="Mas'ul tel raqami"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='receiving_sending_tracks',
            field=models.IntegerField(default=0, verbose_name="Qabul qilish va jo'natish yo'llari"),
        ),
        migrations.AddField(
            model_name='station',
            name='region',
            field=models.CharField(default=' ', help_text='Masalan: Surxondaryo viloyati, Boysun tumani', max_length=150, verbose_name='Hududiy joylashuvi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='switch_type_1_11',
            field=models.IntegerField(default=0, verbose_name='1/11 turi soni'),
        ),
        migrations.AddField(
            model_name='station',
            name='switch_type_1_9',
            field=models.IntegerField(default=0, verbose_name='1/9 turi soni'),
        ),
        migrations.AddField(
            model_name='station',
            name='switches_count',
            field=models.IntegerField(default=0, verbose_name="Strelkali o'tkazmalar soni"),
        ),
        migrations.AddField(
            model_name='station',
            name='total_track_length',
            field=models.FloatField(default=0.0, verbose_name="Ushbu yo'llar jami masofasi (metr)"),
        ),
        migrations.AddField(
            model_name='station',
            name='total_tracks',
            field=models.IntegerField(default=0, verbose_name="Yo'llar soni (jami)"),
        ),
        migrations.AlterField(
            model_name='station',
            name='description',
            field=models.TextField(blank=True, verbose_name="Qo'shimcha izoh"),
        ),
    ]
