# Generated by Django 6.0.2 on 2026-02-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_station_dead_end_tracks_station_insulating_joints_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='receiving_sending_tracks',
            field=models.IntegerField(default=0, verbose_name="Qabul-jo'natish yo'llari"),
        ),
        migrations.AlterField(
            model_name='station',
            name='region',
            field=models.CharField(max_length=150, verbose_name='Hududiy joylashuvi'),
        ),
        migrations.AlterField(
            model_name='station',
            name='switch_type_1_11',
            field=models.IntegerField(default=0, verbose_name='1/11 turi'),
        ),
        migrations.AlterField(
            model_name='station',
            name='switch_type_1_9',
            field=models.IntegerField(default=0, verbose_name='1/9 turi'),
        ),
        migrations.AlterField(
            model_name='station',
            name='switches_count',
            field=models.IntegerField(default=0, verbose_name='Strelkalar soni'),
        ),
        migrations.AlterField(
            model_name='station',
            name='total_track_length',
            field=models.FloatField(default=0.0, verbose_name='Jami masofa (metr)'),
        ),
    ]
